/**
 * @author Simon Neufville <simon@xrscodeworks.com / sneufville@teammps.com>
 * Created: June 20 2018 @ 18:46
 */

// Authorization Action Constants
export const AUTH_ACTIONS = {
    SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
    SET_LOGIN_CREDENTIAL: 'SET_LOGIN_CREDENTIAL',
    SET_USER: 'SET_USER',
    SET_AUTH_IN_PROGRESS: 'SET_AUTH_IN_PROGRESS',
    SET_AUTH_ERROR: 'SET_AUTH_ERROR'
};

// Client Action Constants
export const CLIENT_ACTIONS = {
    GET_CLIENTS: 'GET_CLIENTS',
    SET_CLIENTS: 'SET_CLIENTS',
    SET_CLIENTS_LOADING: 'SET_CLIENTS_LOADING',
    SET_CLIENT_ERROR: 'SET_CLIENT_ERROR'
};

// Timesheet Action Constants
export const TIMESHEET_ACTIONS = {
    GET_TIMESHEETS: 'GET_TIMESHEETS',
    SET_TIMESHEETS: 'SET_TIMESHEETS',
    SET_TIMESHEETS_LOADING: 'SET_TIMESHEETS_LOADING',
    SET_TIMESHEETS_ERROR: 'SET_TIMESHEETS_ERROR',
    SET_TIMESHEET_SAVED: 'SET_TIMESHEET_SAVED',
    CREATE_TIMESHEET_ENTRY: 'CREATE_TIMESHEET_ENTRY',
    UPDATE_TIMESHEET_ENTRY: 'UPDATE_TIMESHEET_ENTRY',
    DELETE_TIMESHEET_ENTRY: 'DELETE_TIMESHEET_ENTRY'
};